### PR TITLE
Refactor our Socket Broadcasts to limit the number of updates we send out.

### PR DESCRIPTION
**Pull request by Hiro-Nakamura**
Previously, when sending out real time updates about data to our clients, we used an `{object}-{role}` method where we would figure out which roles could access an object and then send an update to each of those `{object}-{role}` rooms.

users would register themselves into `{object}-{role}` rooms when they would request data.

However, it is possible for an object to be accessible by multiple `{role}`s.  So a particular update would be sent to multiple `{object}-{role}` rooms.  And it is possible that a user is registered in several of those rooms.  So in effect, a user might be getting multiple copies of an update message.

This update, refactors that approach into a `{tenant}-{id}` approach.  Each time a user requests data from the server, we note which pieces of information they are tracking by assigning them into rooms for each row of data: `{tenant}-{id}`

If multiple users request the same data, they are assigned to the same room.

Now when updates are made, they are broadcasted out to the individual `{tenant}-{id}` room. 

The performance benefit here is that
- users will only get notified of a change to a row of data ONLY if they have requested that data
- users will only get 1 copy of a change request.

NOTE: this works along side:
- [api_sails PR 149](https://github.com/digi-serve/ab_service_api_sails/pull/149)
- [appbuilder PR 86](https://github.com/digi-serve/ab_service_appbuilder/pull/86)
- [ab_platform_web PR 514](https://github.com/digi-serve/ab_platform_web/pull/514)
- [core PR 234](https://github.com/digi-serve/appbuilder_class_core/pull/234)

## Release Notes

- [wip] refactor our Sails Broadcasts to our connected clients.
 

## Test Status
This doesn't have a specific e2e test set up for it.  However, most of our `Datacollection` tests and `Process` tests depend on these updates working as we expect them to.  So for now, those existing tests are validating our socket updates are working as expected.

### CODE REVIEW

**Review by nh758 — CHANGES_REQUESTED** [review]
Sorry, unless misunderstanding something... your changes don't consider Scope, which was the whole reason we switched to broadcast rooms by role.

This was an incident last year. See for more details: https://docs.google.com/document/d/16Hp63bH27v54Sq4fTZ0jlH4ABiLmrfLHdRETY2Sut_Y/edit#heading=h.ypry41lepeow

Previously our rooms were `tenantID-objectID`, currently they are `tenantID-roleID-objectID`. [`getRightRoles.js`](https://github.com/digi-serve/ab_service_appbuilder/blob/master/utils/getRightRoles.js) checks against scopes before broadcast.

**Comment by nh758** [comment]
> So it seems like the concern is that we will go back to sending information to users who don't have access to the data due to their scopes.
> 
> However, this update only sends updates to a user if we have **ALREADY GIVEN THEM** that information.
> 
> Scopes will have already prevented us from giving them any information they shouldn't have received when they perform a `findAll()` / `model-get` operation, and right before we return that data to the user, we note the `{uuid}`s of the records we are sending back and then connect the user to those entries.
> 
> Any `Updates` or `Deletes` to those entries will be sent back to those users who have been given those records.
> 
> This should not repeat that previous error.

Thanks for explaining, I agree that this would work for updates/deletes. But what about Create? Some of our apps expect real-time updates on create. This was part of the problem with the scope incident.

Also, not sure if this is relevant, but what if an update changes the scope?

**Comment by Hiro-Nakamura** [comment]
`@ Updates Changing the Scope:`

OK, that's a good point.  In this case we would still be sending the updated data back to the user's browser.  

However, I also don't see how our current situation would be much different than what these changes would introduce.  In either case, we have already given the User the row of data and they have the info in their browser.  Someone makes an update to the row, and that update would get sent to each of the ppl who loaded the data.  

It would be up to their client side code to detect that the updated value no longer passes their scope filter, and then to remove it from display.  It would then be helpful if we added a `DELETE /broadcast/ID` route that would then un associate the user from that row (but if our client side code is still doing `.isValidData()` to check if the data should be displayed, then it won't be critical as the client side will filter the data).

This would be a good time to create an e2e test to demonstrate this behavior.

**Comment by Hiro-Nakamura** [comment]
As for `Create` events where someone would create a new record that would be something we would display to the user:

This is probably something we should have a Team Discussion (or at least You, Me and Ric) to determine how to proceed.

Do we actually need to offer this? Is there an existing requirement in our apps where a user needs to have a display open and see the real time creates of other users showing up on their screen?  

If this is a requirement, then my guess is that it is much more the exception rather than the rule.  I suspect that the vast majority of our Apps are about users working with their own scope of data: data that they have created, and modified.  And that if there is new data they should see, they can wait until the next time they load the page (just like most php or html based pages).

So instead of defaulting to broadcasting the newly Created entry to everyone who might have had access to that data, let's be more deliberate in our apps.

What if instead we add a new option to a `Datacollection` that says: `[] Requires Global Updates`.  Then on Applications that we want to display these realtime creates from other users, we have to use the same datacollection to create the information as we do to display it.  That way, when the `DC` loads it's data, it can send an additional option to the server in the `.findAll()` that says `.requiresGlobalUpdates = true`, and we register this user to a `{tenant}-{datacollection}` room.  Then when that `DC` performs an `ADD` operation we also include the `.requiresGlobalUpdates=true` option to the request, the server side `model-post` can see this option and then broadcast the created data to the `{tenant}-{datacollection}` room.

In this approach we can ensure that users:
- only get 1 update for the operation
- only get the updates if they are using the App that has this feature.  (no need to send it to ALL users if this is only a Finance App requirement)

If there is additional need to add scope information on top of this we could:
- extend this to a `{tenant}-{datacollection}-{role}` type of solution like we did before
- make sure the client side `.isValidData()` properly validates and rejects non scoped data

**Comment by nh758** [comment]
- I was more thinking the reverse case for scope updates. The scenario I imagine is: `User A` updates `Record 1` so that is know in `User B`'s scope. `User B` may expect to see `Record 1` immediately. Again not sure how relevant this is in real use.

- I don't like the idea of handling scope client side, because that means the client already has access to data they shouldn't see, whether or not it actually displays in the UI.

- We can have more discussion around the `Create`.  But, "Do we need to offer this?" Maybe not, but I think in practice a lot of our existing behavior expects this. I know, at least when I looked at this last year, we needed to broadcast creates, even just to the current user, so that different widgets would update properly. 

I'm ok moving forward with this, but we will need to get this well tested with the real apps on staging.

**Comment by Hiro-Nakamura** [comment]
Some more thoughts:

- in the example you give, yes, this update will not alert `User B` about the new record immediately.  He would have to reload the page to then see the record.  And this is where we would need to discuss if this is a relevant feature to add.

- Keep in mind, we primarily handle scope on the server.  The only case where we would have to then rely on client side scoping is when `User A` was already given a record, that record is updated and no longer is in their scope, and the client would have to figure out that it should not be displayed anymore.

- "expected behavior": Keep in mind, this will still broadcast the `CREATE` to the user who performed the create.  That hasn't changed.  We just don't broadcast it to all the roles who might have had a scope that also allowed it.  As it is, this update passes all our e2e tests and operates as we expect (according to our current tests).

I'm all for testing things out with our real applications.  Hey, that is a great case for creating Application based tests too, right?

So, how do we move forward?  This is one of those multi-repository commits that need both sides to be in place before our kitchensink tests pass again.

Do we force them both to commit?  Do we force one, and then let the kitchensink tests run against the other?  Do new versions need to be created before the kitchensink tests pick up the correct versions?

What's the next step?

**Comment by nh758** [comment]
Sure.

My current recommended approach is: 
1. Test all the branches work together using the kitchen-sink "Test Branches" workflow. [Instructions](https://team.digiserve.org/main/pl/q7rcnc48qfymiroenogkjrznzr) (mattermost). 
2. Build custom images for relevant images. Each service should have a "Docker Custom Image" workflow (instructions in README).
3. Test on Staging
4. When we're ready to merge. Update `version.json` in `ab_runtime` #master using the custom images. (This is meant to be a temporary hack to allow tests to pass in the various services. After all merges and workflows have run, the `version.json` should have updated with the newly generated images).

**Comment by nh758** [comment]
[AB-APPBUILDER-32](https://appdev-designs.sentry.io/issues/5210030616/) I think this issue is from this branch, seen on staging2

**Review by wongpratan — APPROVED** [review]

**Pull request merged**
